<!DOCTYPE HTML>
<html>
	<head>
		<link rel="stylesheet" type="text/css" href="/css/notificacoes.css">
	</head>
	<body>
		<div id="bandejaNotificacoes">
			<div class="itemNotificacao">
				<div class="contador">4</div>
				<img src="/img/icones/notificacoes-alertas.png" />
			</div>
			<div class="itemNotificacao">
				<div class="contador">9</div>
				<img src="/img/icones/notificacoes-mensagens.png" />
			</div>
			<div class="itemNotificacao">
				<div class="contador">13</div>
				<img src="/img/icones/notificacoes-configuracoes.png" />
			</div>
		</div>
	</body>
</html>

